CREATE TABLE t_user_account (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255) NOT NULL UNIQUE,
                                password VARCHAR(255) NOT NULL
);

CREATE TABLE t_permission (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) UNIQUE
);

CREATE TABLE user_permissions (
                                  user_id BIGINT NOT NULL,
                                  permission_id BIGINT NOT NULL,
                                  PRIMARY KEY (user_id, permission_id),
                                  CONSTRAINT fk_user_permissions_user FOREIGN KEY (user_id) REFERENCES t_user_account (id) ON DELETE CASCADE,
                                  CONSTRAINT fk_user_permissions_permission FOREIGN KEY (permission_id) REFERENCES t_permission (id) ON DELETE CASCADE
);