CREATE TABLE t_category (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255),
                            color VARCHAR(255)
);