CREATE TABLE t_post (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title VARCHAR(255),
                         text VARCHAR(255),
                         user_id BIGINT NOT NULL,
                         CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES t_user_account (id) ON DELETE CASCADE
);